apiVersion: batch/v1
kind: Job
metadata:
  name:  vault-alt-k8s-backend
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      name:  vault-alt-k8s-backend
      annotations:
        vault.security/enabled: "true"
        vault.security/vault-addr: "https://vault.default.svc.cluster.local:8200"
        vault.security/vault-tls-secret-name: "vault-consul-ca"
        vault.security/vault-role: "tester"
        vault.security/vault-path: "secrets/v1/some/secrets/path"
        vault.security/k8s-backend-path: "auth/kubernetes-alt/login"
    spec:
      restartPolicy: Never
      serviceAccountName: tester
      containers:
      - name: alpine
        image: alpine
        command:
          - "/bin/sh"
        args:
          - "-c"
          - |
              echo "testing subtree each path as key name with a single value"
              [ -n "$API_KEY" ] && echo "API_KEY: $API_KEY"
              [ -n "$DATABASE_URL" ] && echo "DATABASE_URL: $DATABASE_URL"
              [ -n "$DB_PASSWORD" ] && echo "DB_PASSWORD: $DB_PASSWORD"
              [ -n "$APP_USER" ] && echo "APP_USER: $APP_USER"
              [ -n "$DB_USER" ] && echo "DB_USER: $DB_USER"
              exit 0
        env:
        - name: API_KEY
          value: vault:API_KEY
        resources:
            limits:
              cpu: 0.5m
              memory: 100M
