apiVersion: batch/v1
kind: Job
metadata:
  name:  vault-alt-k8s-backend
  namespace: default
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      name:  vault-alt-k8s-backend
      annotations:
#        vault.secret.manager/enabled: "false"
#        vault.secret.manager/service: "https://vault.vault.svc.cluster.local:8200"
#        vault.secret.manager/auth-path: "auth/kubernetes/sandbox/us-west-2/login"
#        vvault.secret.manager/tls-secret: "vault-ca"
#        vault.secret.manager/role: "manager-tester"
#        vault.secret.manager/path: "secrets/v2/some/secrets/path"
    spec:
      restartPolicy: Never
      serviceAccountName: manager-tester
      containers:
      - name: alpine
        image: alpine
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 3600"
          - |
              echo "testing subtree each path as key name with a single value"
              [ -n "$API_KEY" ] && echo "API_KEY: $API_KEY"
              [ -n "$DATABASE_URL" ] && echo "DATABASE_URL: $DATABASE_URL"
              [ -n "$DB_PASSWORD" ] && echo "DB_PASSWORD: $DB_PASSWORD"
              [ -n "$APP_USER" ] && echo "APP_USER: $APP_USER"
              [ -n "$DB_USER" ] && echo "DB_USER: $DB_USER"
              exit 0
        resources:
            limits:
              cpu: 0.5m
              memory: 100M
