apiVersion: batch/v1
kind: Job
metadata:
  name:  vault-auto-detect-command
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      name:  vault-auto-detect-command
      annotations:
        vault.security/enabled: "true"
        vault.security/vault-addr: "https://vault.default.svc.cluster.local:8200"
        vault.security/vault-role: "milton"
        vault.security/vault-path: "secret_v2/milton"
        vault.security/vault-tls-secret-name: "vault-consul-ca"
        vault.security/vault-use-secret-names-as-keys: "true"
    spec:
      restartPolicy: Never
      serviceAccountName: tester
      containers:
      - name: alpine
        image: docker.io/innovia/secrets-consumer-webhook-detect-cmd:0.1.0
        env:
        - name: API_KEY
          value: vault:API_KEY
        resources:
            limits:
              cpu: 0.5m
              memory: 100M
